plugins {
    id 'application'
    id 'java'
}

group = 'com.github.ipecter'

sourceCompatibility = 17
targetCompatibility = 17

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = 'codemc-repo'
        url = 'https://repo.codemc.org/repository/nms/'
    }
    maven {
        name = 'minecraft-repo'
        url = 'https://libraries.minecraft.net/'
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot:1.17.1-R0.1-SNAPSHOT'
    implementation project(':NMS')
    compileOnly fileTree(dir: '../libs', include: ['*.jar'])
}

task prepareKotlinBuildScriptModel {

}